Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
for DC_AC in [1, 1.2, 1.4]:
    available_G = poa_irradiance['poa_global']
    used_G = available_G.copy()
    used_G[used_G>1000/DC_AC]=1000/DC_AC
    ratio = (available_G.sum()-used_G.sum())/available_G.sum()
    print("For DC/AC ratio = " + str(AC_DC) + ', curtailed energy represents ' + str(round(ratio*100,2)) + '% of available energy')
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[6], line 6[0m
[1;32m      4[0m used_G[used_G[38;5;241m>[39m[38;5;241m1000[39m[38;5;241m/[39mDC_AC][38;5;241m=[39m[38;5;241m1000[39m[38;5;241m/[39mDC_AC
[1;32m      5[0m ratio [38;5;241m=[39m (available_G[38;5;241m.[39msum()[38;5;241m-[39mused_G[38;5;241m.[39msum())[38;5;241m/[39mavailable_G[38;5;241m.[39msum()
[0;32m----> 6[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mFor DC/AC ratio = [39m[38;5;124m"[39m [38;5;241m+[39m [38;5;28mstr[39m([43mAC_DC[49m) [38;5;241m+[39m [38;5;124m'[39m[38;5;124m, curtailed energy represents [39m[38;5;124m'[39m [38;5;241m+[39m [38;5;28mstr[39m([38;5;28mround[39m(ratio[38;5;241m*[39m[38;5;241m100[39m,[38;5;241m2[39m)) [38;5;241m+[39m [38;5;124m'[39m[38;5;132;01m% o[39;00m[38;5;124mf available energy[39m[38;5;124m'[39m)

[0;31mNameError[0m: name 'AC_DC' is not defined

