Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
Rfl_power = Rfl.copy()
Rfl_power_txtred = Rfl_txtred.copy()
AM15G_SiRange = AM15G.copy()

for x in range(nData):
    Rfl_power[x,1] *= np.interp(Rfl_power[x,0], AM15G[:,0],AM15G[:,1])
    Rfl_power_txtred[x,1] *= np.interp(Rfl_power_txtred[x,0], AM15G[:,0],AM15G[:,1])
   
    if Rfl_power[x,0] > 1100:   #only up to bandgap of silicon
        Rfl_power[x,1]=0
        Rfl_power_txtred[x,1]=0
        AM15G_SiRange[x,1]=0
        

Total_W_Si = np.trapezoid( AM15G_SiRange[:,1], x= AM15G_SiRange[:,0], axis=0)

R_W = np.trapezoid(Rfl_power[:,1], x=Rfl_power[:,0], axis=0)
R_W_txtred = np.trapezoid(Rfl_power_txtred[:,1], x=Rfl_power_txtred[:,0], axis=0)

#print(Total_W)
print("Reflected power: " + f"{R_W:.1f}" + " W/m2 (" + f"{100*R_W/Total_W_Si:.1f}" + "%)" )
print("Reflected power with texturing: " + f"{R_W_txtred:.1f}" + " W/m2 (" + f"{100*R_W_txtred/Total_W_Si:.1f}" + "%)" )
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[5], line 15[0m
[1;32m     11[0m         Rfl_power_txtred[x,[38;5;241m1[39m][38;5;241m=[39m[38;5;241m0[39m
[1;32m     12[0m         AM15G_SiRange[x,[38;5;241m1[39m][38;5;241m=[39m[38;5;241m0[39m
[0;32m---> 15[0m Total_W_Si [38;5;241m=[39m [43mnp[49m[38;5;241;43m.[39;49m[43mtrapezoid[49m( AM15G_SiRange[:,[38;5;241m1[39m], x[38;5;241m=[39m AM15G_SiRange[:,[38;5;241m0[39m], axis[38;5;241m=[39m[38;5;241m0[39m)
[1;32m     17[0m R_W [38;5;241m=[39m np[38;5;241m.[39mtrapezoid(Rfl_power[:,[38;5;241m1[39m], x[38;5;241m=[39mRfl_power[:,[38;5;241m0[39m], axis[38;5;241m=[39m[38;5;241m0[39m)
[1;32m     18[0m R_W_txtred [38;5;241m=[39m np[38;5;241m.[39mtrapezoid(Rfl_power_txtred[:,[38;5;241m1[39m], x[38;5;241m=[39mRfl_power_txtred[:,[38;5;241m0[39m], axis[38;5;241m=[39m[38;5;241m0[39m)

File [0;32m/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/numpy/__init__.py:333[0m, in [0;36m__getattr__[0;34m(attr)[0m
[1;32m    330[0m     [38;5;124m"[39m[38;5;124mRemoved in NumPy 1.25.0[39m[38;5;124m"[39m
[1;32m    331[0m     [38;5;28;01mraise[39;00m [38;5;167;01mRuntimeError[39;00m([38;5;124m"[39m[38;5;124mTester was removed in NumPy 1.25.[39m[38;5;124m"[39m)
[0;32m--> 333[0m [38;5;28;01mraise[39;00m [38;5;167;01mAttributeError[39;00m([38;5;124m"[39m[38;5;124mmodule [39m[38;5;132;01m{!r}[39;00m[38;5;124m has no attribute [39m[38;5;124m"[39m
[1;32m    334[0m                      [38;5;124m"[39m[38;5;132;01m{!r}[39;00m[38;5;124m"[39m[38;5;241m.[39mformat([38;5;18m__name__[39m, attr))

[0;31mAttributeError[0m: module 'numpy' has no attribute 'trapezoid'

